version: '3.8'

services:

  mongo:
    image: mongo:7.0.9-rc0
    restart: no
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=sf
    volumes: 
      - ./schema.js:/docker-entrypoint-initdb.d/schema.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/sf --quiet
      interval: 3s
      timeout: 5s
      retries: 30

  backend:
    build: ./
    environment:
      - GONEWS_DB=mongo
    ports:
      - 8081:80
    depends_on:
          mongo:
            condition: service_healthy