version: '3.8'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sf
    volumes: 
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "sf"]
      interval: 3s
      timeout: 5s
      retries: 30

  backend:
    build: ./
    environment:
      - GONEWS_DB=postgres
    ports:
      - 8081:80
    depends_on:
          postgres:
            condition: service_healthy